import type { AllThemes } from "../types/theme";

export const nintendoThemes: AllThemes = {
  CyberSlate: {
    primary: "#228dff",
    "primary-content": "#ffffff",
    secondary: "#7F8289",
    "secondary-content": "#ffffff",
    accent: "#228dff",
    "accent-content": "#ffffff",
    neutral: "#2F3238",
    "neutral-content": "#ffffff",
    "base-100": "#1E2125",
    "base-200": "#26292E",
    "base-300": "#2F3238",
    "base-content": "#ffffff",
    info: "#64B5F6",
    "info-content": "#000000",
    success: "#81C784",
    "success-content": "#000000",
    warning: "#FFB74D",
    "warning-content": "#000000",
    error: "#E57373",
    "error-content": "#000000",
    "--rounded-box": "0",
    "--rounded-btn": "0",
    "--rounded-badge": "0",
    "--animation-btn": "0.3s",
    "--animation-input": "0.2s",
    "--btn-text-case": "uppercase",
    "--btn-focus-scale": "1",
    "--border-btn": "1px",
    "--tab-border": "1px",
    "--tab-radius": "0",
  },
  NeonPulse: {
    primary: "#00ff00",
    "primary-content": "#000000",
    secondary: "#7F8289",
    "secondary-content": "#ffffff",
    accent: "#ff00ff",
    "accent-content": "#000000",
    neutral: "#2F3238",
    "neutral-content": "#ffffff",
    "base-100": "#0D0E10",
    "base-200": "#1A1C20",
    "base-300": "#26292E",
    "base-content": "#ffffff",
    info: "#00ffff",
    "info-content": "#000000",
    success: "#00ff00",
    "success-content": "#000000",
    warning: "#ffff00",
    "warning-content": "#000000",
    error: "#ff0000",
    "error-content": "#000000",
    "--rounded-box": "0",
    "--rounded-btn": "0",
    "--rounded-badge": "0",
    "--animation-btn": "0.3s",
    "--animation-input": "0.2s",
    "--btn-text-case": "uppercase",
    "--btn-focus-scale": "1",
    "--border-btn": "1px",
    "--tab-border": "1px",
    "--tab-radius": "0",
  },
  TechnoEdge: {
    primary: "#ff4d4d",
    "primary-content": "#ffffff",
    secondary: "#7F8289",
    "secondary-content": "#ffffff",
    accent: "#4dffa6",
    "accent-content": "#000000",
    neutral: "#2F3238",
    "neutral-content": "#ffffff",
    "base-100": "#15171A",
    "base-200": "#1E2125",
    "base-300": "#26292E",
    "base-content": "#ffffff",
    info: "#4d94ff",
    "info-content": "#000000",
    success: "#4dffa6",
    "success-content": "#000000",
    warning: "#ffd24d",
    "warning-content": "#000000",
    error: "#ff4d4d",
    "error-content": "#000000",
    "--rounded-box": "0",
    "--rounded-btn": "0",
    "--rounded-badge": "0",
    "--animation-btn": "0.3s",
    "--animation-input": "0.2s",
    "--btn-text-case": "uppercase",
    "--btn-focus-scale": "1",
    "--border-btn": "1px",
    "--tab-border": "1px",
    "--tab-radius": "0",
  },
  DarkMatter: {
    primary: "#9370DB",
    "primary-content": "#ffffff",
    secondary: "#7F8289",
    "secondary-content": "#ffffff",
    accent: "#FF6B6B",
    "accent-content": "#000000",
    neutral: "#2F3238",
    "neutral-content": "#ffffff",
    "base-100": "#121317",
    "base-200": "#1A1C20",
    "base-300": "#26292E",
    "base-content": "#ffffff",
    info: "#4ECDC4",
    "info-content": "#000000",
    success: "#45B649",
    "success-content": "#000000",
    warning: "#FFD700",
    "warning-content": "#000000",
    error: "#FF6B6B",
    "error-content": "#000000",
    "--rounded-box": "4px",
    "--rounded-btn": "2px",
    "--rounded-badge": "2px",
    "--animation-btn": "0.25s",
    "--animation-input": "0.2s",
    "--btn-text-case": "uppercase",
    "--btn-focus-scale": "0.98",
    "--border-btn": "2px",
    "--tab-border": "2px",
    "--tab-radius": "2px",
  },
  NightSky: {
    primary: "#2F3238",
    "primary-content": "#ffffff",
    secondary: "#26292E",
    "secondary-content": "#ffffff",
    accent: "#228dff",
    "accent-content": "#ffffff",
    neutral: "#7F8289",
    "neutral-content": "#ffffff",
    "base-100": "#ffffff",
    "base-200": "#f9fafb",
    "base-300": "#eeeff1",
    "base-content": "#1f2937",
    info: "#3ABFF8",
    "info-content": "#ffffff",
    success: "#36D399",
    "success-content": "#ffffff",
    warning: "#FBBD23",
    "warning-content": "#000000",
    error: "#F87272",
    "error-content": "#ffffff",
    "--rounded-box": "1rem",
    "--rounded-btn": "0.5rem",
    "--rounded-badge": "1.9rem",
    "--animation-btn": "0.25s",
    "--animation-input": "0.2s",
    "--btn-text-case": "uppercase",
    "--btn-focus-scale": "0.95",
    "--border-btn": "1px",
    "--tab-border": "1px",
    "--tab-radius": "0.5rem",
  },
  OceanDepth: {
    primary: "#26292E",
    "primary-content": "#ffffff",
    secondary: "#2F3238",
    "secondary-content": "#ffffff",
    accent: "#1E88E5",
    "accent-content": "#ffffff",
    neutral: "#7F8289",
    "neutral-content": "#ffffff",
    "base-100": "#F0F4F8",
    "base-200": "#E1E8ED",
    "base-300": "#D2DCE1",
    "base-content": "#1f2937",
    info: "#0CA5E9",
    "info-content": "#ffffff",
    success: "#2ECC71",
    "success-content": "#ffffff",
    warning: "#F39C12",
    "warning-content": "#000000",
    error: "#E74C3C",
    "error-content": "#ffffff",
    "--rounded-box": "1.2rem",
    "--rounded-btn": "0.6rem",
    "--rounded-badge": "2rem",
    "--animation-btn": "0.3s",
    "--animation-input": "0.25s",
    "--btn-text-case": "uppercase",
    "--btn-focus-scale": "0.98",
    "--border-btn": "2px",
    "--tab-border": "2px",
    "--tab-radius": "0.6rem",
  },
  SteelGradient: {
    primary: "#7F8289",
    "primary-content": "#ffffff",
    secondary: "#2F3238",
    "secondary-content": "#ffffff",
    accent: "#228dff",
    "accent-content": "#ffffff",
    neutral: "#26292E",
    "neutral-content": "#ffffff",
    "base-100": "#F5F7FA",
    "base-200": "#E4E7EB",
    "base-300": "#D3D7DC",
    "base-content": "#2D3748",
    info: "#4299E1",
    "info-content": "#ffffff",
    success: "#48BB78",
    "success-content": "#ffffff",
    warning: "#ECC94B",
    "warning-content": "#000000",
    error: "#F56565",
    "error-content": "#ffffff",
    "--rounded-box": "0.8rem",
    "--rounded-btn": "0.4rem",
    "--rounded-badge": "1.8rem",
    "--animation-btn": "0.2s",
    "--animation-input": "0.15s",
    "--btn-text-case": "capitalize",
    "--btn-focus-scale": "0.97",
    "--border-btn": "1px",
    "--tab-border": "1px",
    "--tab-radius": "0.4rem",
  },
  customDark: {
    primary: "#2F3238",
    "primary-content": "#ffffff",
    secondary: "#26292E",
    "secondary-content": "#ffffff",
    accent: "#228dff",
    "accent-content": "#ffffff",
    neutral: "#7F8289",
    "neutral-content": "#ffffff",
    "base-100": "#26292E",
    "base-200": "#2F3238",
    "base-300": "#7F8289",
    "base-content": "#ffffff",
    info: "#3498db", // Added info
    "info-content": "#ffffff", // Added info-content
    success: "#43B047", // Added success
    "success-content": "#ffffff", // Added success-content
    warning: "#f1c40f", // Added warning
    "warning-content": "#000000", // Added warning-content
    error: "#e74c3c", // Added error
    "error-content": "#ffffff", // Added error-content
    "--rounded-box": "0",
    "--rounded-btn": "0",
    "--rounded-badge": "0",
    "--animation-btn": "0.25s",
    "--animation-input": "0.2s",
    "--btn-text-case": "uppercase",
    "--btn-focus-scale": "0.95",
    "--border-btn": "1px",
    "--tab-border": "1px",
    "--tab-radius": "0",
  },
  superMario: {
    primary: "#E52521", // Mario Red
    "primary-content": "#FFFFFF",
    secondary: "#FBD000", // Coin Gold
    "secondary-content": "#000000",
    accent: "#5C94FC", // Mario's Overall Blue
    "accent-content": "#FFFFFF",
    neutral: "#F5D04B", // Question Block Yellow
    "neutral-content": "#000000",
    "base-100": "#5C94FC", // Sky Blue
    "base-200": "#3C6CFC", // Darker Sky Blue
    "base-300": "#1C44FC", // Even Darker Sky Blue
    "base-content": "#FFFFFF",
    info: "#FF6B97", // Peach Pink
    "info-content": "#000000",
    success: "#43B047", // 1-Up Mushroom Green
    "success-content": "#FFFFFF",
    warning: "#FF9900", // Fire Flower Orange
    "warning-content": "#000000",
    error: "#D81F26", // Goomba Brown-Red
    "error-content": "#FFFFFF",
    "--rounded-box": "0",
    "--rounded-btn": "0",
    "--rounded-badge": "0",
    "--animation-btn": "0.25s",
    "--animation-input": "0.2s",
    "--btn-text-case": "uppercase",
    "--btn-focus-scale": "0.95",
    "--border-btn": "4px",
    "--tab-border": "4px",
    "--tab-radius": "0",
  },
  mario: {
    primary: "#E52521", // Mario Red
    "primary-content": "#FFFFFF",
    secondary: "#FBD000", // Coin Gold
    "secondary-content": "#000000",
    accent: "#5C94FC", // Mario's Overall Blue
    "accent-content": "#FFFFFF",
    neutral: "#000000", // Black for text and borders
    "neutral-content": "#FFFFFF",
    "base-100": "#E52521", // Mario Red as the main background
    "base-200": "#CE0000", // Darker Mario Red for secondary backgrounds
    "base-300": "#B50000", // Even darker Mario Red for tertiary backgrounds
    "base-content": "#FFFFFF",
    info: "#5C94FC", // Mario's Overall Blue
    "info-content": "#FFFFFF",
    success: "#1E8449", // Green from Luigi's hat
    "success-content": "#FFFFFF",
    warning: "#FBD000", // Coin Gold
    "warning-content": "#000000",
    error: "#E52521", // Mario Red
    "error-content": "#FFFFFF",
    "--rounded-box": "0.5rem",
    "--rounded-btn": "0.25rem",
    "--rounded-badge": "1.9rem",
    "--animation-btn": "0.25s",
    "--animation-input": "0.2s",
    "--btn-text-case": "uppercase",
    "--btn-focus-scale": "0.95",
    "--border-btn": "2px",
    "--tab-border": "2px",
    "--tab-radius": "0.5rem",
  },
  legendOfZelda: {
    primary: "#1e8449",
    "primary-content": "#ffffff",
    secondary: "#ffc107",
    "secondary-content": "#000000",
    accent: "#9c27b0",
    "accent-content": "#ffffff",
    neutral: "#2c3e50",
    "neutral-content": "#ecf0f1",
    "base-100": "#f9f9f9",
    "base-200": "#e0e0e0",
    "base-300": "#d1d1d1",
    "base-content": "#1a2a36",
    info: "#3498db",
    "info-content": "#ffffff",
    success: "#07bc0c",
    "success-content": "#ffffff",
    warning: "#f1c40f",
    "warning-content": "#000000",
    error: "#e74c3c",
    "error-content": "#ffffff",
    "--rounded-box": "0.5rem",
    "--rounded-btn": "0.25rem",
    "--rounded-badge": "0.25rem",
    "--animation-btn": "0.3s",
    "--animation-input": "0.25s",
    "--btn-text-case": "uppercase",
    "--btn-focus-scale": "0.98",
    "--border-btn": "3px",
    "--tab-border": "3px",
    "--tab-radius": "0.5rem",
  },
  metroid: {
    primary: "#ff6b6b",
    "primary-content": "#ffffff",
    secondary: "#4ecdc4",
    "secondary-content": "#ffffff",
    accent: "#feca57",
    "accent-content": "#000000",
    neutral: "#2c3e50",
    "neutral-content": "#ecf0f1",
    "base-100": "#1a1a2e",
    "base-200": "#16213e",
    "base-300": "#0f3460",
    "base-content": "#e94560",
    info: "#3498db",
    "info-content": "#ffffff",
    success: "#07bc0c",
    "success-content": "#ffffff",
    warning: "#f1c40f",
    "warning-content": "#000000",
    error: "#e74c3c",
    "error-content": "#ffffff",
    "--rounded-box": "0rem",
    "--rounded-btn": "0rem",
    "--rounded-badge": "0rem",
    "--animation-btn": "0.2s",
    "--animation-input": "0.2s",
    "--btn-text-case": "lowercase",
    "--btn-focus-scale": "1",
    "--border-btn": "1px",
    "--tab-border": "1px",
    "--tab-radius": "0",
  },
  donkeyKong: {
    primary: "#8B4513",
    "primary-content": "#ffffff",
    secondary: "#FFD700",
    "secondary-content": "#000000",
    accent: "#32CD32",
    "accent-content": "#ffffff",
    neutral: "#3E2723",
    "neutral-content": "#ffffff",
    "base-100": "#FAFAFA",
    "base-200": "#EEEEEE",
    "base-300": "#E0E0E0",
    "base-content": "#212121",
    info: "#2196F3",
    "info-content": "#ffffff",
    success: "#4CAF50",
    "success-content": "#ffffff",
    warning: "#FFC107",
    "warning-content": "#000000",
    error: "#F44336",
    "error-content": "#ffffff",
    "--rounded-box": "0.5rem",
    "--rounded-btn": "0.5rem",
    "--rounded-badge": "0.5rem",
    "--animation-btn": "0.3s",
    "--animation-input": "0.2s",
    "--btn-text-case": "uppercase",
    "--btn-focus-scale": "0.95",
    "--border-btn": "2px",
    "--tab-border": "2px",
    "--tab-radius": "0.5rem",
  },
  pokemon: {
    primary: "#FF0000",
    "primary-content": "#ffffff",
    secondary: "#3B4CCA",
    "secondary-content": "#ffffff",
    accent: "#FFDE00",
    "accent-content": "#000000",
    neutral: "#B3A125",
    "neutral-content": "#ffffff",
    "base-100": "#ffffff",
    "base-200": "#f8f8f8",
    "base-300": "#f0f0f0",
    "base-content": "#1f2937",
    info: "#0075BE",
    "info-content": "#ffffff",
    success: "#4DAD5B",
    "success-content": "#ffffff",
    warning: "#FFA500",
    "warning-content": "#000000",
    error: "#FB1B1B",
    "error-content": "#ffffff",
    "--rounded-box": "1rem",
    "--rounded-btn": "0.5rem",
    "--rounded-badge": "1.9rem",
    "--animation-btn": "0.25s",
    "--animation-input": "0.2s",
    "--btn-text-case": "uppercase",
    "--btn-focus-scale": "0.95",
    "--border-btn": "1px",
    "--tab-border": "1px",
    "--tab-radius": "0.5rem",
  },
};
