// src/themes.ts

export interface Theme {
  name: string;
  displayName: string;
  colors: {
    bgColor: string;
    textColor: string;
    borderColor: string;
    headerBg: string;
    cardBg: string;
    highlightColor: string;
    secondaryColor: string;
    accentColor: string;
    mutedColor: string;
    linkColor: string;
    linkHoverColor: string;
  };
}

export const themes: Theme[] = [
  {
    name: 'retroComputer',
    displayName: 'Retro Computer',
    colors: {
      bgColor: '#002b36',
      textColor: '#839496',
      borderColor: '#586e75',
      headerBg: '#073642',
      cardBg: '#001e26',
      highlightColor: '#b58900',
      secondaryColor: '#2aa198',
      accentColor: '#cb4b16',
      mutedColor: '#657b83',
      linkColor: '#268bd2',
      linkHoverColor: '#6c71c4',
    },
  },
  {
    name: 'zelda',
    displayName: 'Zelda',
    colors: {
      bgColor: '#1a2b1e',
      textColor: '#e0f8cf',
      borderColor: '#b0d990',
      headerBg: '#244c28',
      cardBg: '#2f4f2f',
      highlightColor: '#f7d51d',
      secondaryColor: '#71aa34',
      accentColor: '#ff6b6b',
      mutedColor: '#a0c090',
      linkColor: '#40e0d0',
      linkHoverColor: '#00ced1',
    },
  },
  {
    name: 'zeldaForest',
    displayName: 'Zelda Forest',
    colors: {
      bgColor: '#1e3f20',
      textColor: '#e8f3e9',
      borderColor: '#7caa2d',
      headerBg: '#2e5931',
      cardBg: '#1e3f20',
      highlightColor: '#ffd700',
      secondaryColor: '#3cb371',
      accentColor: '#ff7f50',
      mutedColor: '#8fbc8f',
      linkColor: '#98fb98',
      linkHoverColor: '#00fa9a',
    },
  },
  {
    name: 'zeldaDesert',
    displayName: 'Zelda Desert',
    colors: {
      bgColor: '#c2b280',
      textColor: '#3d1f00',
      borderColor: '#8b4513',
      headerBg: '#deb887',
      cardBg: '#f4a460',
      highlightColor: '#ff8c00',
      secondaryColor: '#d2691e',
      accentColor: '#20b2aa',
      mutedColor: '#d2b48c',
      linkColor: '#008080',
      linkHoverColor: '#40e0d0',
    },
  },
  {
    name: 'zeldaTwilight',
    displayName: 'Zelda Twilight',
    colors: {
      bgColor: '#1f1f3d',
      textColor: '#e6e6fa',
      borderColor: '#483d8b',
      headerBg: '#191970',
      cardBg: '#2f2f4f',
      highlightColor: '#ffd700',
      secondaryColor: '#9370db',
      accentColor: '#ff69b4',
      mutedColor: '#6a5acd',
      linkColor: '#00ffff',
      linkHoverColor: '#87cefa',
    },
  },
  {
    name: 'mario',
    displayName: 'Mario',
    colors: {
      bgColor: '#5c94fc',
      textColor: '#ffffff',
      borderColor: '#fc0000',
      headerBg: '#000000',
      cardBg: '#2840a8',
      highlightColor: '#fca044',
      secondaryColor: '#fc0000',
      accentColor: '#ffd700',
      mutedColor: '#87ceeb',
      linkColor: '#1e90ff',
      linkHoverColor: '#ffd700',
    },
  },
  {
    name: 'marioUnderwater',
    displayName: 'Mario Underwater',
    colors: {
      bgColor: '#0077be',
      textColor: '#e0ffff',
      borderColor: '#4682b4',
      headerBg: '#00008b',
      cardBg: '#1e90ff',
      highlightColor: '#ffd700',
      secondaryColor: '#00ffff',
      accentColor: '#ff6347',
      mutedColor: '#87ceeb',
      linkColor: '#f0e68c',
      linkHoverColor: '#fafad2',
    },
  },
  {
    name: 'marioCastle',
    displayName: 'Mario Castle',
    colors: {
      bgColor: '#4a4a4a',
      textColor: '#e0e0e0',
      borderColor: '#8b4513',
      headerBg: '#800000',
      cardBg: '#696969',
      highlightColor: '#ffa500',
      secondaryColor: '#cd853f',
      accentColor: '#ff4500',
      mutedColor: '#a9a9a9',
      linkColor: '#ffd700',
      linkHoverColor: '#ff6347',
    },
  },
  {
    name: 'marioRainbow',
    displayName: 'Mario Rainbow',
    colors: {
      bgColor: '#ff69b4',
      textColor: '#ffffff',
      borderColor: '#ff1493',
      headerBg: '#8a2be2',
      cardBg: '#00bfff',
      highlightColor: '#ffff00',
      secondaryColor: '#00ff00',
      accentColor: '#ff4500',
      mutedColor: '#9370db',
      linkColor: '#00ffff',
      linkHoverColor: '#7fffd4',
    },
  },
  {
    name: 'metroid',
    displayName: 'Metroid',
    colors: {
      bgColor: '#1a0a2b',
      textColor: '#e6adc9',
      borderColor: '#4b46a8',
      headerBg: '#2c1052',
      cardBg: '#200f3d',
      highlightColor: '#00ffff',
      secondaryColor: '#fa8e2e',
      accentColor: '#ff6b97',
      mutedColor: '#8a7a99',
      linkColor: '#bd93f9',
      linkHoverColor: '#ff79c6',
    },
  },
  {
    name: 'pokemonClassic',
    displayName: 'Pokemon Classic',
    colors: {
      bgColor: '#f0f0f0',
      textColor: '#333333',
      borderColor: '#3c5aa6',
      headerBg: '#cc0000',
      cardBg: '#ffffff',
      highlightColor: '#ffcb05',
      secondaryColor: '#2a75bb',
      accentColor: '#ff9900',
      mutedColor: '#bdbdbd',
      linkColor: '#3c5aa6',
      linkHoverColor: '#2a75bb',
    },
  },
  {
    name: 'sonic',
    displayName: 'Sonic',
    colors: {
      bgColor: '#0066cc',
      textColor: '#ffffff',
      borderColor: '#ffd700',
      headerBg: '#003399',
      cardBg: '#0099ff',
      highlightColor: '#ffff00',
      secondaryColor: '#ff6600',
      accentColor: '#66cc33',
      mutedColor: '#3399cc',
      linkColor: '#ffcc00',
      linkHoverColor: '#ff9900',
    },
  },
  {
    name: 'pacman',
    displayName: 'Pac-Man',
    colors: {
      bgColor: '#000000',
      textColor: '#ffffff',
      borderColor: '#0000ff',
      headerBg: '#000080',
      cardBg: '#000033',
      highlightColor: '#ffff00',
      secondaryColor: '#00ffff',
      accentColor: '#ff0000',
      mutedColor: '#808080',
      linkColor: '#ff69b4',
      linkHoverColor: '#ff1493',
    },
  },
  {
    name: 'tetris',
    displayName: 'Tetris',
    colors: {
      bgColor: '#000000',
      textColor: '#ffffff',
      borderColor: '#00ff00',
      headerBg: '#0000ff',
      cardBg: '#202020',
      highlightColor: '#ff0000',
      secondaryColor: '#00ffff',
      accentColor: '#ffff00',
      mutedColor: '#808080',
      linkColor: '#ff00ff',
      linkHoverColor: '#ff69b4',
    },
  },
  {
    name: 'donkeyKong',
    displayName: 'Donkey Kong',
    colors: {
      bgColor: '#964b00',
      textColor: '#ffd700',
      borderColor: '#8b4513',
      headerBg: '#800000',
      cardBg: '#cd853f',
      highlightColor: '#ff4500',
      secondaryColor: '#32cd32',
      accentColor: '#1e90ff',
      mutedColor: '#d2691e',
      linkColor: '#00ffff',
      linkHoverColor: '#00ced1',
    },
  },
  {
    name: 'kirby',
    displayName: 'Kirby',
    colors: {
      bgColor: '#ffb7c5',
      textColor: '#8b4513',
      borderColor: '#ff69b4',
      headerBg: '#ff1493',
      cardBg: '#ffc0cb',
      highlightColor: '#ffd700',
      secondaryColor: '#00ced1',
      accentColor: '#32cd32',
      mutedColor: '#dda0dd',
      linkColor: '#1e90ff',
      linkHoverColor: '#00bfff',
    },
  },
  {
    name: 'zeldaSheikah',
    displayName: 'Zelda Sheikah',
    colors: {
      bgColor: '#2c3e50',
      textColor: '#ecf0f1',
      borderColor: '#3498db',
      headerBg: '#34495e',
      cardBg: '#465c71',
      highlightColor: '#e67e22',
      secondaryColor: '#1abc9c',
      accentColor: '#e74c3c',
      mutedColor: '#95a5a6',
      linkColor: '#3498db',
      linkHoverColor: '#2980b9',
    },
  },
  {
    name: 'zeldaGerudo',
    displayName: 'Zelda Gerudo',
    colors: {
      bgColor: '#c0392b',
      textColor: '#f9ebea',
      borderColor: '#f39c12',
      headerBg: '#962d22',
      cardBg: '#d64541',
      highlightColor: '#f1c40f',
      secondaryColor: '#e67e22',
      accentColor: '#16a085',
      mutedColor: '#d35400',
      linkColor: '#f39c12',
      linkHoverColor: '#f1c40f',
    },
  },
  {
    name: 'marioMushroomKingdom',
    displayName: 'Mario Mushroom Kingdom',
    colors: {
      bgColor: '#87ceeb',
      textColor: '#000000',
      borderColor: '#32cd32',
      headerBg: '#4169e1',
      cardBg: '#98fb98',
      highlightColor: '#ff4500',
      secondaryColor: '#ffd700',
      accentColor: '#ff69b4',
      mutedColor: '#add8e6',
      linkColor: '#0000cd',
      linkHoverColor: '#0000ff',
    },
  },
  {
    name: 'marioBowsersCastle',
    displayName: 'Mario Bowser\'s Castle',
    colors: {
      bgColor: '#2f0000',
      textColor: '#ffa07a',
      borderColor: '#8b0000',
      headerBg: '#4b0000',
      cardBg: '#3f0000',
      highlightColor: '#ffd700',
      secondaryColor: '#ff4500',
      accentColor: '#00ff00',
      mutedColor: '#8b4513',
      linkColor: '#ff6347',
      linkHoverColor: '#ff7f50',
    },
  },
  {
    name: 'castlevaniaClassic',
    displayName: 'Castlevania Classic',
    colors: {
      bgColor: '#1a0000',
      textColor: '#d3d3d3',
      borderColor: '#8b0000',
      headerBg: '#400000',
      cardBg: '#2a0000',
      highlightColor: '#ffd700',
      secondaryColor: '#c0c0c0',
      accentColor: '#4169e1',
      mutedColor: '#696969',
      linkColor: '#ff6347',
      linkHoverColor: '#ff4500',
    },
  },
  {
    name: 'castlevaniaSymphony',
    displayName: 'Castlevania Symphony',
    colors: {
      bgColor: '#191970',
      textColor: '#e6e6fa',
      borderColor: '#4b0082',
      headerBg: '#000080',
      cardBg: '#1e1e5a',
      highlightColor: '#ffd700',
      secondaryColor: '#9370db',
      accentColor: '#ff1493',
      mutedColor: '#483d8b',
      linkColor: '#00ffff',
      linkHoverColor: '#1e90ff',
    },
  },
  {
    name: 'donkeyKongJungle',
    displayName: 'Donkey Kong Jungle',
    colors: {
      bgColor: '#228b22',
      textColor: '#ffff00',
      borderColor: '#8b4513',
      headerBg: '#006400',
      cardBg: '#32cd32',
      highlightColor: '#ffa500',
      secondaryColor: '#ff4500',
      accentColor: '#1e90ff',
      mutedColor: '#3cb371',
      linkColor: '#ffd700',
      linkHoverColor: '#ff6347',
    },
  },
  {
    name: 'donkeyKongIce',
    displayName: 'Donkey Kong Ice',
    colors: {
      bgColor: '#e0ffff',
      textColor: '#191970',
      borderColor: '#4169e1',
      headerBg: '#87ceeb',
      cardBg: '#b0e0e6',
      highlightColor: '#ff69b4',
      secondaryColor: '#00bfff',
      accentColor: '#32cd32',
      mutedColor: '#add8e6',
      linkColor: '#0000ff',
      linkHoverColor: '#1e90ff',
    },
  },
  {
    name: 'megaMan',
    displayName: 'Mega Man',
    colors: {
      bgColor: '#0000ff',
      textColor: '#ffffff',
      borderColor: '#00ffff',
      headerBg: '#000080',
      cardBg: '#0080ff',
      highlightColor: '#ffff00',
      secondaryColor: '#00ff00',
      accentColor: '#ff0000',
      mutedColor: '#4169e1',
      linkColor: '#ffa500',
      linkHoverColor: '#ff4500',
    },
  },
  // Add more themes here...
];

export function getThemeByName(name: string): Theme {
  return themes.find((theme) => theme.name === name) || themes[0];
}
