export interface Theme {
  name: string;
  displayName: string;
  colors: {
    bgColor: string;
    textColor: string;
    borderColor: string;
    headerBg: string;
    cardBg: string;
    highlightColor: string;
    secondaryColor: string;
    accentColor: string;
    mutedColor: string;
    linkColor: string;
    linkHoverColor: string;
  };
}

export const themes: Theme[] = [
  // General Themes
  {
    name: 'retroComputer',
    displayName: 'Retro Computer',
    colors: {
      bgColor: '#002b36',
      textColor: '#839496',
      borderColor: '#586e75',
      headerBg: '#073642',
      cardBg: '#001e26',
      highlightColor: '#b58900',
      secondaryColor: '#2aa198',
      accentColor: '#cb4b16',
      mutedColor: '#657b83',
      linkColor: '#268bd2',
      linkHoverColor: '#6c71c4',
    },
  },

  // Mario Franchise
  {
    name: 'marioClassic',
    displayName: 'Mario: Classic',
    colors: {
      bgColor: '#5c94fc',
      textColor: '#ffffff',
      borderColor: '#fc0000',
      headerBg: '#000000',
      cardBg: '#2840a8',
      highlightColor: '#fca044',
      secondaryColor: '#fc0000',
      accentColor: '#ffd700',
      mutedColor: '#87ceeb',
      linkColor: '#1e90ff',
      linkHoverColor: '#ffd700',
    },
  },
  {
    name: 'marioUnderwater',
    displayName: 'Mario: Underwater',
    colors: {
      bgColor: '#0077be',
      textColor: '#e0ffff',
      borderColor: '#4682b4',
      headerBg: '#00008b',
      cardBg: '#1e90ff',
      highlightColor: '#ffd700',
      secondaryColor: '#00ffff',
      accentColor: '#ff6347',
      mutedColor: '#87ceeb',
      linkColor: '#f0e68c',
      linkHoverColor: '#fafad2',
    },
  },
  {
    name: 'marioCastle',
    displayName: 'Mario: Castle',
    colors: {
      bgColor: '#4a4a4a',
      textColor: '#e0e0e0',
      borderColor: '#8b4513',
      headerBg: '#800000',
      cardBg: '#696969',
      highlightColor: '#ffa500',
      secondaryColor: '#cd853f',
      accentColor: '#ff4500',
      mutedColor: '#a9a9a9',
      linkColor: '#ffd700',
      linkHoverColor: '#ff6347',
    },
  },
  {
    name: 'marioRainbow',
    displayName: 'Mario: Rainbow Road',
    colors: {
      bgColor: '#ff69b4',
      textColor: '#ffffff',
      borderColor: '#ff1493',
      headerBg: '#8a2be2',
      cardBg: '#00bfff',
      highlightColor: '#ffff00',
      secondaryColor: '#00ff00',
      accentColor: '#ff4500',
      mutedColor: '#9370db',
      linkColor: '#00ffff',
      linkHoverColor: '#7fffd4',
    },
  },
  {
    name: 'marioMushroomKingdom',
    displayName: 'Mario: Mushroom Kingdom',
    colors: {
      bgColor: '#87ceeb',
      textColor: '#000000',
      borderColor: '#32cd32',
      headerBg: '#4169e1',
      cardBg: '#98fb98',
      highlightColor: '#ff4500',
      secondaryColor: '#ffd700',
      accentColor: '#ff69b4',
      mutedColor: '#add8e6',
      linkColor: '#0000cd',
      linkHoverColor: '#0000ff',
    },
  },
  {
    name: 'marioBowsersCastle',
    displayName: 'Mario: Bowser\'s Castle',
    colors: {
      bgColor: '#2f0000',
      textColor: '#ffa07a',
      borderColor: '#8b0000',
      headerBg: '#4b0000',
      cardBg: '#3f0000',
      highlightColor: '#ffd700',
      secondaryColor: '#ff4500',
      accentColor: '#00ff00',
      mutedColor: '#8b4513',
      linkColor: '#ff6347',
      linkHoverColor: '#ff7f50',
    },
  },
  {
    name: 'marioPeach',
    displayName: 'Mario: Princess Peach',
    colors: {
      bgColor: '#FFB7C5',
      textColor: '#FF69B4',
      borderColor: '#FF1493',
      headerBg: '#FFC0CB',
      cardBg: '#FFE4E1',
      highlightColor: '#FF69B4',
      secondaryColor: '#FF1493',
      accentColor: '#FFA07A',
      mutedColor: '#FFB6C1',
      linkColor: '#FF69B4',
      linkHoverColor: '#FF1493',
    },
  },
  {
    name: 'marioLuigi',
    displayName: 'Mario: Luigi',
    colors: {
      bgColor: '#7CFC00',
      textColor: '#006400',
      borderColor: '#32CD32',
      headerBg: '#90EE90',
      cardBg: '#98FB98',
      highlightColor: '#00FF00',
      secondaryColor: '#32CD32',
      accentColor: '#0000FF',
      mutedColor: '#3CB371',
      linkColor: '#006400',
      linkHoverColor: '#008000',
    },
  },
  {
    name: 'marioBowser',
    displayName: 'Mario: Bowser',
    colors: {
      bgColor: '#8B4513',
      textColor: '#FFA500',
      borderColor: '#D2691E',
      headerBg: '#A0522D',
      cardBg: '#CD853F',
      highlightColor: '#FF4500',
      secondaryColor: '#FFA500',
      accentColor: '#00FF00',
      mutedColor: '#DEB887',
      linkColor: '#FFD700',
      linkHoverColor: '#FFA500',
    },
  },

  // Zelda Franchise
  {
    name: 'zeldaClassic',
    displayName: 'Zelda: Classic',
    colors: {
      bgColor: '#1a2b1e',
      textColor: '#e0f8cf',
      borderColor: '#b0d990',
      headerBg: '#244c28',
      cardBg: '#2f4f2f',
      highlightColor: '#f7d51d',
      secondaryColor: '#71aa34',
      accentColor: '#ff6b6b',
      mutedColor: '#a0c090',
      linkColor: '#40e0d0',
      linkHoverColor: '#00ced1',
    },
  },
  {
    name: 'zeldaForest',
    displayName: 'Zelda: Forest',
    colors: {
      bgColor: '#1e3f20',
      textColor: '#e8f3e9',
      borderColor: '#7caa2d',
      headerBg: '#2e5931',
      cardBg: '#1e3f20',
      highlightColor: '#ffd700',
      secondaryColor: '#3cb371',
      accentColor: '#ff7f50',
      mutedColor: '#8fbc8f',
      linkColor: '#98fb98',
      linkHoverColor: '#00fa9a',
    },
  },
  {
    name: 'zeldaDesert',
    displayName: 'Zelda: Desert',
    colors: {
      bgColor: '#c2b280',
      textColor: '#3d1f00',
      borderColor: '#8b4513',
      headerBg: '#deb887',
      cardBg: '#f4a460',
      highlightColor: '#ff8c00',
      secondaryColor: '#d2691e',
      accentColor: '#20b2aa',
      mutedColor: '#d2b48c',
      linkColor: '#008080',
      linkHoverColor: '#40e0d0',
    },
  },
  {
    name: 'zeldaTwilight',
    displayName: 'Zelda: Twilight',
    colors: {
      bgColor: '#1f1f3d',
      textColor: '#e6e6fa',
      borderColor: '#483d8b',
      headerBg: '#191970',
      cardBg: '#2f2f4f',
      highlightColor: '#ffd700',
      secondaryColor: '#9370db',
      accentColor: '#ff69b4',
      mutedColor: '#6a5acd',
      linkColor: '#00ffff',
      linkHoverColor: '#87cefa',
    },
  },
  {
    name: 'zeldaSheikah',
    displayName: 'Zelda: Sheikah',
    colors: {
      bgColor: '#2c3e50',
      textColor: '#ecf0f1',
      borderColor: '#3498db',
      headerBg: '#34495e',
      cardBg: '#465c71',
      highlightColor: '#e67e22',
      secondaryColor: '#1abc9c',
      accentColor: '#e74c3c',
      mutedColor: '#95a5a6',
      linkColor: '#3498db',
      linkHoverColor: '#2980b9',
    },
  },
  {
    name: 'zeldaGerudo',
    displayName: 'Zelda: Gerudo',
    colors: {
      bgColor: '#c0392b',
      textColor: '#f9ebea',
      borderColor: '#f39c12',
      headerBg: '#962d22',
      cardBg: '#d64541',
      highlightColor: '#f1c40f',
      secondaryColor: '#e67e22',
      accentColor: '#16a085',
      mutedColor: '#d35400',
      linkColor: '#f39c12',
      linkHoverColor: '#f1c40f',
    },
  },
  {
    name: 'zeldaPrincess',
    displayName: 'Zelda: Princess Zelda',
    colors: {
      bgColor: '#FFF0F5',
      textColor: '#8B008B',
      borderColor: '#DA70D6',
      headerBg: '#FFB6C1',
      cardBg: '#FFC0CB',
      highlightColor: '#FF69B4',
      secondaryColor: '#DDA0DD',
      accentColor: '#9370DB',
      mutedColor: '#D8BFD8',
      linkColor: '#8B008B',
      linkHoverColor: '#9400D3',
    },
  },
  {
    name: 'zeldaLink',
    displayName: 'Zelda: Link',
    colors: {
      bgColor: '#228B22',
      textColor: '#F0E68C',
      borderColor: '#DAA520',
      headerBg: '#32CD32',
      cardBg: '#3CB371',
      highlightColor: '#FFD700',
      secondaryColor: '#ADFF2F',
      accentColor: '#1E90FF',
      mutedColor: '#90EE90',
      linkColor: '#F0E68C',
      linkHoverColor: '#FFD700',
    },
  },
  {
    name: 'zeldaGanondorf',
    displayName: 'Zelda: Ganondorf',
    colors: {
      bgColor: '#8B0000',
      textColor: '#FFD700',
      borderColor: '#B8860B',
      headerBg: '#A52A2A',
      cardBg: '#CD5C5C',
      highlightColor: '#FF4500',
      secondaryColor: '#FF8C00',
      accentColor: '#4B0082',
      mutedColor: '#DC143C',
      linkColor: '#FFD700',
      linkHoverColor: '#FFA500',
    },
  },
  {
    name: 'zeldaDeku',
    displayName: 'Zelda: Deku',
    colors: {
      bgColor: '#556B2F',
      textColor: '#FAFAD2',
      borderColor: '#8FBC8F',
      headerBg: '#6B8E23',
      cardBg: '#9ACD32',
      highlightColor: '#ADFF2F',
      secondaryColor: '#7CFC00',
      accentColor: '#FFD700',
      mutedColor: '#9ACD32',
      linkColor: '#FAFAD2',
      linkHoverColor: '#FFFACD',
    },
  },
  {
    name: 'zeldaZora',
    displayName: 'Zelda: Zora',
    colors: {
      bgColor: '#4682B4',
      textColor: '#E0FFFF',
      borderColor: '#87CEFA',
      headerBg: '#5F9EA0',
      cardBg: '#B0E0E6',
      highlightColor: '#00FFFF',
      secondaryColor: '#1E90FF',
      accentColor: '#7FFFD4',
      mutedColor: '#ADD8E6',
      linkColor: '#E0FFFF',
      linkHoverColor: '#F0FFFF',
    },
  },
  {
    name: 'zeldaGoron',
    displayName: 'Zelda: Goron',
    colors: {
      bgColor: '#8B4513',
      textColor: '#FFE4B5',
      borderColor: '#D2691E',
      headerBg: '#A0522D',
      cardBg: '#CD853F',
      highlightColor: '#FF8C00',
      secondaryColor: '#DEB887',
      accentColor: '#B22222',
      mutedColor: '#F4A460',
      linkColor: '#FFE4B5',
      linkHoverColor: '#FFDAB9',
    },
  },
  // Metroid Franchise
  {
    name: 'metroidClassic',
    displayName: 'Metroid: Classic',
    colors: {
      bgColor: '#1a0a2b',
      textColor: '#e6adc9',
      borderColor: '#4b46a8',
      headerBg: '#2c1052',
      cardBg: '#200f3d',
      highlightColor: '#00ffff',
      secondaryColor: '#fa8e2e',
      accentColor: '#ff6b97',
      mutedColor: '#8a7a99',
      linkColor: '#bd93f9',
      linkHoverColor: '#ff79c6',
    },
  },

  // Pokemon Franchise
  {
    name: 'pokemonClassic',
    displayName: 'Pokemon: Classic',
    colors: {
      bgColor: '#f0f0f0',
      textColor: '#333333',
      borderColor: '#3c5aa6',
      headerBg: '#cc0000',
      cardBg: '#ffffff',
      highlightColor: '#ffcb05',
      secondaryColor: '#2a75bb',
      accentColor: '#ff9900',
      mutedColor: '#bdbdbd',
      linkColor: '#3c5aa6',
      linkHoverColor: '#2a75bb',
    },
  },

  // Sonic Franchise
  {
    name: 'sonicClassic',
    displayName: 'Sonic: Classic',
    colors: {
      bgColor: '#0066cc',
      textColor: '#ffffff',
      borderColor: '#ffd700',
      headerBg: '#003399',
      cardBg: '#0099ff',
      highlightColor: '#ffff00',
      secondaryColor: '#ff6600',
      accentColor: '#66cc33',
      mutedColor: '#3399cc',
      linkColor: '#ffcc00',
      linkHoverColor: '#ff9900',
    },
  },
  {
    name: 'sonicTails',
    displayName: 'Sonic: Tails',
    colors: {
      bgColor: '#FFA500',
      textColor: '#FFFFFF',
      borderColor: '#FF8C00',
      headerBg: '#FFD700',
      cardBg: '#FAFAD2',
      highlightColor: '#FF4500',
      secondaryColor: '#FFA07A',
      accentColor: '#1E90FF',
      mutedColor: '#F0E68C',
      linkColor: '#FFFFFF',
      linkHoverColor: '#FFD700',
    },
  },
  {
    name: 'sonicKnuckles',
    displayName: 'Sonic: Knuckles',
    colors: {
      bgColor: '#B22222',
      textColor: '#FFFFFF',
      borderColor: '#8B0000',
      headerBg: '#DC143C',
      cardBg: '#CD5C5C',
      highlightColor: '#FF4500',
      secondaryColor: '#FF6347',
      accentColor: '#32CD32',
      mutedColor: '#FA8072',
      linkColor: '#FFFFFF',
      linkHoverColor: '#FFD700',
    },
  },
  {
    name: 'sonicShadow',
    displayName: 'Sonic: Shadow',
    colors: {
      bgColor: '#2F4F4F',
      textColor: '#DC143C',
      borderColor: '#4B0082',
      headerBg: '#000000',
      cardBg: '#696969',
      highlightColor: '#FF4500',
      secondaryColor: '#FF69B4',
      accentColor: '#FFD700',
      mutedColor: '#A9A9A9',
      linkColor: '#DC143C',
      linkHoverColor: '#FF1493',
    },
  },

  // Pac-Man Franchise
  {
    name: 'pacmanClassic',
    displayName: 'Pac-Man: Classic',
    colors: {
      bgColor: '#000000',
      textColor: '#ffffff',
      borderColor: '#0000ff',
      headerBg: '#000080',
      cardBg: '#000033',
      highlightColor: '#ffff00',
      secondaryColor: '#00ffff',
      accentColor: '#ff0000',
      mutedColor: '#808080',
      linkColor: '#ff69b4',
      linkHoverColor: '#ff1493',
    },
  },

  // Tetris
  {
    name: 'tetrisClassic',
    displayName: 'Tetris: Classic',
    colors: {
      bgColor: '#000000',
      textColor: '#ffffff',
      borderColor: '#00ff00',
      headerBg: '#0000ff',
      cardBg: '#202020',
      highlightColor: '#ff0000',
      secondaryColor: '#00ffff',
      accentColor: '#ffff00',
      mutedColor: '#808080',
      linkColor: '#ff00ff',
      linkHoverColor: '#ff69b4',
    },
  },

  // Donkey Kong Franchise
  {
    name: 'donkeyKongClassic',
    displayName: 'Donkey Kong: Classic',
    colors: {
      bgColor: '#964b00',
      textColor: '#ffd700',
      borderColor: '#8b4513',
      headerBg: '#800000',
      cardBg: '#cd853f',
      highlightColor: '#ff4500',
      secondaryColor: '#32cd32',
      accentColor: '#1e90ff',
      mutedColor: '#d2691e',
      linkColor: '#00ffff',
      linkHoverColor: '#00ced1',
    },
  },
  {
    name: 'donkeyKongJungle',
    displayName: 'Donkey Kong: Jungle',
    colors: {
      bgColor: '#228b22',
      textColor: '#ffff00',
      borderColor: '#8b4513',
      headerBg: '#006400',
      cardBg: '#32cd32',
      highlightColor: '#ffa500',
      secondaryColor: '#ff4500',
      accentColor: '#1e90ff',
      mutedColor: '#3cb371',
      linkColor: '#ffd700',
      linkHoverColor: '#ff6347',
    },
  },
  {
    name: 'donkeyKongIce',
    displayName: 'Donkey Kong: Ice',
    colors: {
      bgColor: '#e0ffff',
      textColor: '#191970',
      borderColor: '#4169e1',
      headerBg: '#87ceeb',
      cardBg: '#b0e0e6',
      highlightColor: '#ff69b4',
      secondaryColor: '#00bfff',
      accentColor: '#32cd32',
      mutedColor: '#add8e6',
      linkColor: '#0000ff',
      linkHoverColor: '#1e90ff',
    },
  },
  {
    name: 'donkeyKongCranky',
    displayName: 'Donkey Kong: Cranky Kong',
    colors: {
      bgColor: '#8B4513',
      textColor: '#F4A460',
      borderColor: '#A0522D',
      headerBg: '#D2691E',
      cardBg: '#CD853F',
      highlightColor: '#DEB887',
      secondaryColor: '#FFE4B5',
      accentColor: '#32CD32',
      mutedColor: '#D2B48C',
      linkColor: '#F4A460',
      linkHoverColor: '#FFDAB9',
    },
  },

  // Kirby Franchise
  {
    name: 'kirbyClassic',
    displayName: 'Kirby: Classic',
    colors: {
      bgColor: '#ffb7c5',
      textColor: '#8b4513',
      borderColor: '#ff69b4',
      headerBg: '#ff1493',
      cardBg: '#ffc0cb',
      highlightColor: '#ffd700',
      secondaryColor: '#00ced1',
      accentColor: '#32cd32',
      mutedColor: '#dda0dd',
      linkColor: '#1e90ff',
      linkHoverColor: '#00bfff',
    },
  },

  // Castlevania Franchise
  {
    name: 'castlevaniaClassic',
    displayName: 'Castlevania: Classic',
    colors: {
      bgColor: '#1a0000',
      textColor: '#d3d3d3',
      borderColor: '#8b0000',
      headerBg: '#400000',
      cardBg: '#2a0000',
      highlightColor: '#ffd700',
      secondaryColor: '#c0c0c0',
      accentColor: '#4169e1',
      mutedColor: '#696969',
      linkColor: '#ff6347',
      linkHoverColor: '#ff4500',
    },
  },
  {
    name: 'castlevaniaSymphony',
    displayName: 'Castlevania: Symphony',
    colors: {
      bgColor: '#191970',
      textColor: '#e6e6fa',
      borderColor: '#4b0082',
      headerBg: '#000080',
      cardBg: '#1e1e5a',
      highlightColor: '#ffd700',
      secondaryColor: '#9370db',
      accentColor: '#ff1493',
      mutedColor: '#483d8b',
      linkColor: '#00ffff',
      linkHoverColor: '#1e90ff',
    },
  },

  // Mega Man Franchise
  {
    name: 'megaManClassic',
    displayName: 'Mega Man: Classic',
    colors: {
      bgColor: '#0000ff',
      textColor: '#ffffff',
      borderColor: '#00ffff',
      headerBg: '#000080',
      cardBg: '#0080ff',
      highlightColor: '#ffff00',
      secondaryColor: '#00ff00',
      accentColor: '#ff0000',
      mutedColor: '#4169e1',
      linkColor: '#ffa500',
      linkHoverColor: '#ff4500',
    },
  },
];

export function getThemeByName(name: string): Theme {
  return themes.find((theme) => theme.name === name) || themes[0];
}